config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord 

    validates :name, presence: true, uniqueness: true 
end 

app/models/user.rb
class User < ApplicationRecord

    validates :email, :password_digest, :session_token, presence: true 
    validates :password, length: { minimum: 6, allow_nil: true }
    after_initialize :ensure_session_token 

    attr_reader :password 

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        (user && user.is_password?(password)) ? user : nil 
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
    end

    def self.generate_session_token
          SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token 
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64 
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in? 
    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user 
    end
    
    def current_user
        @current_user ||= User.find_by_session_token(session[:session_token])
    end

    def logged_in? 
        !!current_user
    end 
    
    def logout! 
        session[:session_token] = nil 
        if current_user
        @current_user.reset_session_token!
        end 
    end

    def require_login
        redirect_to new_session_url unless logged_in? 
    end

    def require_logout 
        redirect_to user_url if logged_in?
    end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index 
        @bands = Band.all 
        render :index 
    end

    def new 
        @band = Band.new 
        render :new 
    end

    def create 
        @band = Band.new(band_params)
        if @band.save 
            redirect_to band_url(@band)
        else 
            flash[:errors] = @band.errors.full_messages
            redirect_to :new 
        end
    end
    
    def show 
        @band = Band.find(params[:id])
    end

    def edit 
       @band = Band.find(params[:id]) 
    end

    def update 
        @band = Band.find(params[:id])
        if @band.update(band_params)
           redirect_to band_url(@band)
        else 
           flash[:errors] = @band.errors.full_messages
           redirect_to :new 
        end
    end

    def destroy 
        @band = Band.find(params[:id])
        @band.destroy 
        redirect_to bands_url 
    end

    private 
    def band_params 
        params.require(:band).permit(:name)
    end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new  
        render :new 
    end 

    def create 
        user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        if user 
            login!(user)
            redirect_to user_url(user)
        else 
            render :new 
        end 
    end

    def destroy 
        logout!
        redirect_to new_session_url 
    end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new  
        @user = User.new
        render :new 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
          login!(@user)
          redirect_to user_url(@user)
        else 
          flash[:errors] = @user.errors.full_messages
          redirect_to new_user_url
        end

        
    end

    def show 
        @user = User.find(params[:id])
    end

    private 
    def user_params
        params.require(:user).permit(:email, :password)
    end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/edit.html.erb
<h2>Edit <%=@band.name%> </h2>
<form action='<%= band_url(@band) %>' method='post'>
    <input type='hidden' name='_method' value='patch'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for='name'>Name: </label>
    <input type='text' id='name' name='band[name]'>
    <input type='submit' value='Submit'>
</form>
<br>
<a href='<%=band_url(@band)%>'>Cancle</a>

app/views/bands/index.html.erb
<h2>BANDS</h2>
  <ul>
    <% @bands.each do |band| %>
    <li><a class='band_link' href='<%=band_url(band)%>'><%= band.name %></li></a>
    <br>
    <% end %>
  </ul>
<br><br>
<a href='<%=new_band_url%>'>Creat New Band!</a>

app/views/bands/new.html.erb
<h2>Creat New Band</h2>
<form action='<%= bands_url %>' method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for='name'>Name: </label>
    <input type='text' id='name' name='band[name]'>
    <input type='submit' value='Submit'>
</form>
<br>
<a href='<%=bands_url%>'>Cancle</a>

app/views/bands/show.html.erb
<h2><%= @band.name %></h2>
<a href='<%=bands_url%>'>Show all bands!</a><br><br>
<a href='<%=edit_band_url%>'>Edit the band!</a><br><br>

<form action='<%=band_url(@band)%>' method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type='hidden' name='_method' value='delete'>
    <input type="submit" value="Delete Band">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Music App</h1>
    <% if logged_in? %>
      <form action='<%=session_url%>' method='post'>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type='hidden' name='_method' value='delete'>
        <input type='submit' value='Sign Out'>
      </form>
    <% else %>
      <a href='<%= new_session_url %>'>Sign In</a>
      <br><br>
      <a href='<%= new_user_url %>'>Sign Up</a>
    <% end %>
    
      <% if flash[:errors] %>
        <%= flash[:errors] %>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h2> Sign Up</h2>
<form action='<%=users_url%>' method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for = 'email'> Email: </label>
        <input type='text' id = 'email' name='user[email]'>
        <br><br>
    <label for='password'> Password: </label>
        <input type='text' id='password' name='user[password]'>  
        <br><br>
    <input type = 'submit' value='Sign up'>
</form>

app/views/users/show.html.erb
<h2>Hi <%=@user.email%> Welcome to Music App !</h2>
<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/SNice.svg/440px-SNice.svg.png'>